<?php
  include_once 'install-funcs.inc.php';

  // Default action is to configure
  $configure_action = '3';

  // Check if previous configuration file exists
  if (file_exists($CONFIG_FILE)) {
    if (NON_INTERACTIVE) {
      $configure_action = '2'; // Save existing by default if non interactive
    } else {
      $configure_action = '0';
    }
  }

  while ($configure_action !== '1' && $configure_action !== '2' &&
      $configure_action !== '3') {

    // File exists. Does user want to just go with previous configuration?
    print "Previous configuration file found. What would you like to do?\n" .
      "   [1] Use previous configuration.\n" .
      "   [2] Re-configure using current configuration as defaults.\n" .
      "   [3] Re-configure using default configuration as defaults.\n" .
      'Enter the number corresponding to the action you would like to take: ';

    $configure_action = trim(fgets(STDIN));
    print "\n";
  }

  if ($configure_action === '1') {
    // Do not configure. File is in place and user wants to use it.
    print "Using previous configuration.\n";

    // pre-install depends on this variable
    $CONFIG = parse_ini_file($CONFIG_FILE);
  } else if ($configure_action === '2') {
    // Use current config as default and re-configure interactively.
    print "Using current config file as defaults, and re-configuring.\n";

    $CONFIG = array_merge($DEFAULTS, parse_ini_file($CONFIG_FILE));
  } else if ($configure_action === '3') {
    // Use defaults and re-configure interactively.
    print "Reverting to default configuration and re-configuring.\n";

    $CONFIG = $DEFAULTS;
  }

  if ($configure_action === '2' || $configure_action === '3') {
    // interactively configure
    foreach ($CONFIG as $key => $value) {
      // These parameters are configured specially below...
      if ($key === 'CURVE_SERVICES' || $key === 'DEAGG_SERVICES') {
        continue;
      }

      $secure = (stripos($key, 'pass') !== false);
      $unknown = !isset($DEFAULTS[$key]);

      $CONFIG[$key] = configure(
        $key, // Name of option
        $value, // Default value
        (isset($HELP_TEXT[$key]))?$HELP_TEXT[$key]:null, // Help text
        $secure, // Should echo be turned off for inputs?
        $unknown // Is this a known/unkown option?
      );
    }


    $curveServices = array();
    // Should we keep previously configured curve services?
    if (isset($CONFIG['CURVE_SERVICES'])) {
      $oldServices = explode(',', $CONFIG['CURVE_SERVICES']);
      foreach ($oldServices as $oldService) {
        $serviceInfo = explode('|', $oldService);

        if (count($serviceInfo) < 3) {
          continue; // Not a valid service config, skip ...
        }

        print "\nExisting service \"" . $serviceInfo[0] . "\" found...\n";
        print "  SERVICE_META = " . $serviceInfo[1] . "\n";
        print "  SERVICE_HANDLER = " . $serviceInfo[2] . "\n";

        if (promptYesNo('Keep existing configured curve service "' .
            $serviceInfo[0] . '"?', true)) {
          $curveServices[] = $oldService;
        }
      }
    }

    while (promptYesNo("\nConfigure additional curve service?", false)) {
      $curveServices[] = configureWebService('hazard');
    }
    $CONFIG['CURVE_SERVICES'] = implode(',', $curveServices);


    $deaggServices = array();
    // Should we keep previously configured deagg services?
    if (isset($CONFIG['DEAGG_SERVICES'])) {
      $oldServices = explode(',', $CONFIG['DEAGG_SERVICES']);
      foreach ($oldServices as $oldService) {
        $serviceInfo = explode('|', $oldService);

        if (count($serviceInfo) < 3) {
          continue; // Not a valid service config, skip ...
        }

        print "\nExisting service \"" . $serviceInfo[0] . "\" found...\n";
        print "  SERVICE_META = " . $serviceInfo[1] . "\n";
        print "  SERVICE_HANDLER = " . $serviceInfo[2] . "\n";

        if (promptYesNo('Keep existing configured deaggregation service "' .
            $serviceInfo[0] . '"?', true)) {
          $deaggServices[] = $oldService;
        }
      }
    }

    while(promptYesNo("\nConfigured additional deagg service?", false)) {
      $deaggServices[] = configureWebService('deaggregation');
    }
    $CONFIG['DEAGG_SERVICES'] = implode(',', $deaggServices);


    // build config file content
    $ini = '; this file was autogenerated' . "\n" .
           '; at ' . date('r') . "\n";
    foreach ($CONFIG as $key => $value) {
      $help = 'no help available for this option';
      if (isset($HELP_TEXT[$key])) {
        $help = $HELP_TEXT[$key];
      }
      $ini .= sprintf("\n; %s\n%s = '%s'\n", $help, $key, $value);
    }

    // write config file
    file_put_contents($CONFIG_FILE, $ini);
  }
?>
